#!/usr/bin/env ruby -rubygems

# spread repo directory name
SpreadDir = ".spread"

# kit helpers
require_relative './project.rb'
require_relative './git.rb'
require_relative './deploy.rb'

# check if working directory is inside spread project
spread = detectSpread Dir.pwd
if spread
    Spread = spread
    # defines Git function
    git = setupGit Spread
    if git
        Git = git
    end
end

# load commands
Commands = {}
Dir[File.dirname(__FILE__) + '/cmd/*.rb'].each{ |file|
    require file
}

# if no subcommand, print help screen
if ARGV.length < 1
    puts "kit - Git for Kubernetes prototype"
    puts "Try one of these commands:"
    for cmdName in Commands.keys
        puts "- #{cmdName}"
    end
    exit 1
end

cmd = ARGV[0]
args = ARGV[1..-1]
Commands[cmd].call(args, nil)
