#!/bin/bash

# spread repo directory name
S_DIR=".spread"

# Directory script is in
SRC_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# import global functions
source "${SRC_DIR}/project.sh"
source "${SRC_DIR}/git.sh"

# detect spread project
detectSpread $(pwd)

if [ ! -z "$SPREAD" ]; then
    setupGit
fi

# load commands
for file in ${SRC_DIR}/cmd/*.sh; do
    source $file
done

params=("$@")
eval "${1}Command ${params[@]:1}"
